/**
 * Subset of common OBD-II DTC codes with Spanish descriptions.
 * Full database has 10k+ codes; this covers the most frequent ones.
 */
export const DTC_CODES: Record<string, string> = {
  // ─── P0 — Powertrain, generic ──────────────────────────────────────────────
  P0100: 'Sensor de flujo de masa de aire (MAF) — circuito defectuoso',
  P0101: 'Sensor de flujo de masa de aire (MAF) — rango/rendimiento',
  P0102: 'Sensor de flujo de masa de aire (MAF) — señal baja',
  P0103: 'Sensor de flujo de masa de aire (MAF) — señal alta',
  P0110: 'Sensor de temperatura del aire de admisión — circuito defectuoso',
  P0111: 'Sensor de temperatura del aire de admisión — rango/rendimiento',
  P0112: 'Sensor de temperatura del aire de admisión — señal baja',
  P0113: 'Sensor de temperatura del aire de admisión — señal alta',
  P0115: 'Sensor de temperatura del refrigerante — circuito defectuoso',
  P0116: 'Sensor de temperatura del refrigerante — rango/rendimiento',
  P0117: 'Sensor de temperatura del refrigerante — señal baja',
  P0118: 'Sensor de temperatura del refrigerante — señal alta',
  P0120: 'Sensor de posición del acelerador (TPS) — circuito A defectuoso',
  P0121: 'Sensor de posición del acelerador (TPS) — rango/rendimiento A',
  P0122: 'Sensor de posición del acelerador (TPS) — señal baja A',
  P0123: 'Sensor de posición del acelerador (TPS) — señal alta A',
  P0128: 'Termostato — temperatura por debajo de lo normal',
  P0130: 'Sonda lambda banco 1 sensor 1 — circuito defectuoso',
  P0131: 'Sonda lambda banco 1 sensor 1 — señal baja',
  P0132: 'Sonda lambda banco 1 sensor 1 — señal alta',
  P0133: 'Sonda lambda banco 1 sensor 1 — respuesta lenta',
  P0134: 'Sonda lambda banco 1 sensor 1 — sin actividad',
  P0135: 'Sonda lambda banco 1 sensor 1 — calefactor defectuoso',
  P0136: 'Sonda lambda banco 1 sensor 2 — circuito defectuoso',
  P0137: 'Sonda lambda banco 1 sensor 2 — señal baja',
  P0138: 'Sonda lambda banco 1 sensor 2 — señal alta',
  P0141: 'Sonda lambda banco 1 sensor 2 — calefactor defectuoso',
  P0150: 'Sonda lambda banco 2 sensor 1 — circuito defectuoso',
  P0170: 'Sistema de combustible — mezcla pobre banco 1',
  P0171: 'Sistema de combustible — mezcla muy pobre banco 1',
  P0172: 'Sistema de combustible — mezcla muy rica banco 1',
  P0174: 'Sistema de combustible — mezcla muy pobre banco 2',
  P0175: 'Sistema de combustible — mezcla muy rica banco 2',
  P0190: 'Sensor de presión de combustible — circuito defectuoso',
  P0191: 'Sensor de presión de combustible — rango/rendimiento',
  P0192: 'Sensor de presión de combustible — señal baja',
  P0193: 'Sensor de presión de combustible — señal alta',
  P0200: 'Circuito del inyector — defecto general',
  P0201: 'Circuito del inyector — cilindro 1',
  P0202: 'Circuito del inyector — cilindro 2',
  P0203: 'Circuito del inyector — cilindro 3',
  P0204: 'Circuito del inyector — cilindro 4',
  P0205: 'Circuito del inyector — cilindro 5',
  P0206: 'Circuito del inyector — cilindro 6',
  P0217: 'Motor sobrecalentado',
  P0219: 'Sobrevelocidad del motor',
  P0230: 'Circuito de la bomba de combustible — defecto primario',
  P0261: 'Circuito del inyector del cilindro 1 — voltaje bajo',
  P0262: 'Circuito del inyector del cilindro 1 — voltaje alto',
  P0300: 'Fallo de encendido detectado — cilindro aleatorio',
  P0301: 'Fallo de encendido — cilindro 1',
  P0302: 'Fallo de encendido — cilindro 2',
  P0303: 'Fallo de encendido — cilindro 3',
  P0304: 'Fallo de encendido — cilindro 4',
  P0305: 'Fallo de encendido — cilindro 5',
  P0306: 'Fallo de encendido — cilindro 6',
  P0316: 'Fallo de encendido detectado en los primeros 1000 rpm',
  P0320: 'Sensor de posición del árbol de distribución — fallo de entrada',
  P0321: 'Sensor de posición del árbol de distribución — rango/rendimiento',
  P0322: 'Sensor de posición del árbol de distribución — sin señal',
  P0325: 'Sensor de detonación (knock) — circuito defectuoso banco 1',
  P0326: 'Sensor de detonación (knock) — rango/rendimiento banco 1',
  P0327: 'Sensor de detonación (knock) — señal baja banco 1',
  P0328: 'Sensor de detonación (knock) — señal alta banco 1',
  P0335: 'Sensor de posición del cigüeñal (CKP) — circuito A defectuoso',
  P0336: 'Sensor de posición del cigüeñal (CKP) — rango/rendimiento A',
  P0337: 'Sensor de posición del cigüeñal (CKP) — señal baja A',
  P0338: 'Sensor de posición del cigüeñal (CKP) — señal alta A',
  P0339: 'Sensor de posición del cigüeñal (CKP) — señal intermitente A',
  P0340: 'Sensor de posición del árbol de levas (CMP) — circuito A banco 1',
  P0341: 'Sensor de posición del árbol de levas (CMP) — rango A banco 1',
  P0342: 'Sensor de posición del árbol de levas (CMP) — señal baja A banco 1',
  P0343: 'Sensor de posición del árbol de levas (CMP) — señal alta A banco 1',
  P0400: 'Recirculación de gases de escape (EGR) — flujo defectuoso',
  P0401: 'Recirculación de gases de escape (EGR) — flujo insuficiente detectado',
  P0402: 'Recirculación de gases de escape (EGR) — flujo excesivo detectado',
  P0403: 'Recirculación de gases de escape (EGR) — circuito defectuoso',
  P0404: 'Recirculación de gases de escape (EGR) — rango/rendimiento',
  P0410: 'Sistema de inyección de aire secundario — funcionamiento incorrecto banco 1',
  P0411: 'Sistema de inyección de aire secundario — flujo incorrecto banco 1',
  P0420: 'Sistema catalizador — eficiencia por debajo del umbral banco 1',
  P0421: 'Catalizador — eficiencia por debajo umbral banco 1',
  P0430: 'Sistema catalizador — eficiencia por debajo del umbral banco 2',
  P0440: 'Sistema EVAP — fallo general',
  P0441: 'Sistema EVAP — flujo de purga incorrecto',
  P0442: 'Sistema EVAP — fuga pequeña detectada',
  P0443: 'Válvula de purga del sistema EVAP — circuito defectuoso',
  P0444: 'Válvula de purga del sistema EVAP — circuito abierto',
  P0445: 'Válvula de purga del sistema EVAP — cortocircuito alto',
  P0446: 'Válvula de ventilación del sistema EVAP — circuito defectuoso',
  P0455: 'Sistema EVAP — fuga grande detectada',
  P0456: 'Sistema EVAP — fuga muy pequeña detectada',
  P0460: 'Sensor de nivel de combustible — circuito defectuoso',
  P0461: 'Sensor de nivel de combustible — rango/rendimiento',
  P0462: 'Sensor de nivel de combustible — señal baja',
  P0463: 'Sensor de nivel de combustible — señal alta',
  P0480: 'Relé del ventilador de refrigeración 1 — circuito defectuoso',
  P0481: 'Relé del ventilador de refrigeración 2 — circuito defectuoso',
  P0500: 'Sensor de velocidad del vehículo (VSS) — defecto',
  P0501: 'Sensor de velocidad del vehículo (VSS) — rango/rendimiento',
  P0502: 'Sensor de velocidad del vehículo (VSS) — señal baja',
  P0503: 'Sensor de velocidad del vehículo (VSS) — señal intermitente',
  P0505: 'Sistema de control de ralentí — fallo',
  P0506: 'Sistema de control de ralentí — RPM bajas',
  P0507: 'Sistema de control de ralentí — RPM altas',
  P0513: 'Clave de inmovilizador incorrecta',
  P0520: 'Sensor de presión del aceite de motor — circuito defectuoso',
  P0521: 'Sensor de presión del aceite de motor — rango/rendimiento',
  P0522: 'Sensor de presión del aceite de motor — señal baja',
  P0523: 'Sensor de presión del aceite de motor — señal alta',
  P0530: 'Sensor de presión del aire acondicionado — circuito defectuoso',
  P0560: 'Voltaje del sistema — defecto',
  P0562: 'Voltaje del sistema — bajo',
  P0563: 'Voltaje del sistema — alto',
  P0571: 'Interruptor de freno/embrague — circuito A defectuoso',
  P0600: 'Bus de comunicación serie — fallo de enlace',
  P0601: 'Módulo de control del motor (ECM/PCM) — error de memoria',
  P0602: 'Módulo de control (PCM) — no programado',
  P0603: 'Módulo de control (PCM) — error de memoria KAM',
  P0604: 'Módulo de control (PCM) — error de RAM',
  P0605: 'Módulo de control (PCM) — error de ROM',
  P0606: 'Módulo de control (ECM/PCM) — procesador defectuoso',
  P0700: 'Sistema de control de transmisión — fallo indicado',
  P0705: 'Sensor de rango de transmisión — circuito defectuoso',
  P0706: 'Sensor de rango de transmisión — rango/rendimiento',
  P0710: 'Sensor de temperatura del fluido de transmisión — circuito defectuoso',
  P0711: 'Sensor de temperatura del fluido de transmisión — rango/rendimiento',
  P0712: 'Sensor de temperatura del fluido de transmisión — señal baja',
  P0713: 'Sensor de temperatura del fluido de transmisión — señal alta',
  P0715: 'Sensor de velocidad de entrada de transmisión — defecto',
  P0720: 'Sensor de velocidad de salida de transmisión — defecto',
  P0730: 'Relación de transmisión incorrecta',
  P0731: 'Relación de primera marcha incorrecta',
  P0732: 'Relación de segunda marcha incorrecta',
  P0733: 'Relación de tercera marcha incorrecta',
  P0734: 'Relación de cuarta marcha incorrecta',
  P0735: 'Relación de quinta marcha incorrecta',
  P0740: 'Solenoide de convertidor de par — fallo del circuito',
  P0741: 'Solenoide de convertidor de par — atascado apagado',
  P0750: 'Solenoide de cambio A — fallo del circuito',
  P0755: 'Solenoide de cambio B — fallo del circuito',
  P0760: 'Solenoide de cambio C — fallo del circuito',
  P0765: 'Solenoide de cambio D — fallo del circuito',
  // ─── P1/P2 — Fabricante ────────────────────────────────────────────────────
  P1000: 'Sistema OBD — ciclo de conducción incompleto',
  // ─── B — Carrocería ────────────────────────────────────────────────────────
  B0001: 'Airbag conductor — circuito defectuoso',
  B0002: 'Airbag copiloto — circuito defectuoso',
  B0010: 'Pretensor del cinturón conductor — circuito defectuoso',
  // ─── C — Chasis ────────────────────────────────────────────────────────────
  C0000: 'Sistema de control de tracción — velocidad de la rueda',
  C0035: 'Sensor de velocidad de la rueda delantera derecha — defecto',
  C0040: 'Sensor de velocidad de la rueda delantera izquierda — defecto',
  C0045: 'Sensor de velocidad de la rueda trasera derecha — defecto',
  C0050: 'Sensor de velocidad de la rueda trasera izquierda — defecto',
  C0110: 'Motor del sistema ABS — defecto',
  C0121: 'Válvula solenoide del ABS — defecto',
  C0265: 'Relé del motor ABS — circuito activo',
  // ─── U — Red de comunicación ───────────────────────────────────────────────
  U0001: 'Bus CAN de alta velocidad — fallo de comunicación',
  U0100: 'Pérdida de comunicación con ECM/PCM',
  U0101: 'Pérdida de comunicación con módulo de control de transmisión (TCM)',
  U0121: 'Pérdida de comunicación con módulo de control del ABS',
  U0155: 'Pérdida de comunicación con cuadro de instrumentos',
};

/** Lookup DTC description. Returns fallback if not found. */
export const getDtcDescription = (code: string): string => {
  const upper = code.toUpperCase();
  return DTC_CODES[upper] ?? 'Código desconocido — consulta con un mecánico';
};

/** Decode raw 2-byte DTC from OBD-II response bytes. */
export const decodeDtcBytes = (b1: number, b2: number): string => {
  const types = ['P', 'C', 'B', 'U'];
  const type = types[(b1 & 0xc0) >> 6];
  const digit2 = (b1 & 0x30) >> 4;
  const digit3 = b1 & 0x0f;
  const digit4 = (b2 & 0xf0) >> 4;
  const digit5 = b2 & 0x0f;
  return `${type}${digit2}${digit3.toString(16).toUpperCase()}${digit4.toString(16).toUpperCase()}${digit5.toString(16).toUpperCase()}`;
};
